#server:
#  port: 8081
  
spring:
  application:
    name: hr-service
  cloud:
    consul:
      host: localhost
      port: 8500
    
management:
  endpoints:
    web:
      exposure:
        include: health,info

  