#server:
#  port: 8081
  
spring:
  application:
    name: hr-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        
management:
  endpoints:
    web:
      exposure:
        include: health,info

  